version: "3.8"

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: laravel-to-yup
    extra_hosts:
            - 'host.docker.internal:host-gateway'
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null